server:
  port: 8080

spring:
  application:
    name: jvm-lab

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

  metrics:
      distribution:
        histogram:
          http.server.requests: true
        percentiles:
          http.server.requests: 0.95,0.99
