apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvm-lab-app
  namespace: jvm-lab
  labels:
    app: jvm-lab
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvm-lab
      env: production
  template:
    metadata:
      labels:
        app: jvm-lab
        env: production
    spec:
      containers:
      - name: jvm-lab
        image: PLACEHOLDER_IMAGE
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 20
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: jvm-lab-service
  namespace: jvm-lab
spec:
  selector:
    app: jvm-lab
    env: production
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jvm-lab-hpa
  namespace: jvm-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jvm-lab-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
